//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camionsito
{
    using System;
    using System.Collections.Generic;
    
    public partial class viaje
    {
        public int id { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_camion { get; set; }
        public Nullable<int> lugar_salida { get; set; }
        public Nullable<int> lugar_llegada { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<System.DateTime> fecha_llegada { get; set; }
    
        public virtual camion camion { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual destino destino { get; set; }
        public virtual origen origen { get; set; }
    }
}
